version: "3.8"

services:
  quantumvault:
    container_name: quantumvault_container
    image: quantumvault-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATA_PATH=/storage
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - quantumvault_data:/storage  # Attach the named volume explicitly

volumes:
  quantumvault_data:  # Ensure the volume is defined
    name: quantumvault_data
